from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from django.conf import settings
import os

urlpatterns = patterns('',
	# (r'^epub/$', 'isbookshelf.views.get_epub'),
	# (r'^en',include('isbookshelf.urls_en')),
	(r'^shell$', 'isbookshelf.staff.Shell'),
	(r'^$', 'isbookshelf.general.MainPage'),
	(r'^entry/?(.*)$', 'isbookshelf.general.EntryPage'),
	(r'^author/?(.*)$', 'isbookshelf.general.AuthorPage'),
	(r'^group/?(.*)$', 'isbookshelf.general.GroupPage'),
	(r'^tag/?(.*)$', 'isbookshelf.general.TagPage'),
	(r'^keyword/?(.*)$', 'isbookshelf.general.KeywordPage'),
	(r'^year/?(.*)$', 'isbookshelf.general.YearPage'),
	(r'^search/?(.*)$', 'isbookshelf.general.SearchPage'),
	(r'^category$', 'isbookshelf.general.CategoryPage'),
	(r'^link/?$', 'isbookshelf.general.LinkPage'),
	(r'^renew/?$', 'isbookshelf.general.RenewPage'),
	(r'^help/?$', 'isbookshelf.general.HelpPage'),
	(r'^contact/?$', 'isbookshelf.general.ContactPage'),
	(r'^rss/?$','isbookshelf.general.RssPage'),

	(r'^contents$', 'isbookshelf.general.ContentsPage'),


	(r'^login$','isbookshelf.authorized.LoginPage'),
	(r'^login/$','isbookshelf.authorized.LoginPage'),
	(r'^logout$','isbookshelf.authorized.LogoutPage'),

	(r'^epub$', 'isbookshelf.authorized.DownloadPage'),
	(r'^zip$', 'isbookshelf.authorized.zip'),
	(r'^zipper$', 'isbookshelf.authorized.zipper'),

	(r'^upload_form$', 'isbookshelf.authorized.WritePage'),
	(r'^dashboard$', 'isbookshelf.authorized.DashboardPage'),
	(r'^add_entry$', 'isbookshelf.authorized.EditEntryPage'),
	(r'^edit_entry$', 'isbookshelf.authorized.edit_entry'),
	(r'^approval$', 'isbookshelf.authorized.ApprovalPage'),
	(r'^setting$', 'isbookshelf.authorized.SettingPage'),
	(r'^select_author$', 'isbookshelf.ajax.select_author'),
	(r'^select_yearth$', 'isbookshelf.ajax.select_yearth'),
	(r'^preview$', 'isbookshelf.ajax.preview'),
	(r'^ajax_save$', 'isbookshelf.ajax.ajax_save'),
	(r'^change_favorite$', 'isbookshelf.ajax.change_favorite'),
	(r'^ajax/(.*)$', 'isbookshelf.ajax.ajax'),
	(r'^api/(.*)$', 'isbookshelf.api.ajax'),
	(r'^recommend/(.*)$', 'isbookshelf.ajax.recommend'),
	(r'^remove_book$', 'isbookshelf.ajax.remove_book'),

	(r'^edit_group$', 'isbookshelf.staff.edit_group'),
	(r'^edit_author$', 'isbookshelf.staff.edit_author'),
	(r'^edit_tag$', 'isbookshelf.staff.edit_tag'),
	(r'^edit_keyword$', 'isbookshelf.staff.edit_keyword'),
	(r'^edit_renew$', 'isbookshelf.staff.edit_renew'),
	(r'^create_group$', 'isbookshelf.staff.create_group'),
	(r'^create_author$', 'isbookshelf.staff.create_author'),

	(r'^forbidden$', 'isbookshelf.error.forbidden'),
	(r'^notfound$', 'isbookshelf.error.notfound'),
	(r'^servererror$', 'isbookshelf.error.servererror'),
	(r'^page-template.xpgt$', 'isbookshelf.error.pagetemplate'),
	# (r'^export_author$', 'isbookshelf.views.export_author'),
	# (r'^upload$', 'isbookshelf.views.upload'),
	# (r'^upload_entry$', 'isbookshelf.views.upload_entry'),
	# (r'^image_list$', 'isbookshelf.views.image_list'),
	# (r'^delete_img$', 'isbookshelf.views.delete_img'),
	# (r'^upload_numeric$', 'isbookshelf.views.upload_numeric'),
	# (r'^add_entry$', 'isbookshelf.views.add_entry'),
	# (r'^isdl_edit$', 'isbookshelf.views.isdl_edit'),
	# (r'^download$', 'isbookshelf.views.download'),
	# (r'^add_author$', 'isbookshelf.views.add_author'),
	# (r'^gallery$', 'isbookshelf.views.gallery'),
	# (r'^change_book_name$', 'isbookshelf.views.change_book_name'),
	# (r'^approval$', 'isbookshelf.views.approval'),
	# (r'^search_result$', 'isbookshelf.views.search_result'),
	# (r'^isdlstyle$', 'isbookshelf.views.isdlstyle'),
	# (r'^fileupload/$', 'isbookshelf.views.upload'),
	# (r'^get_books_form$', 'isbookshelf.views.get_books_form'),
	# (r'^get_preview$', 'isbookshelf.views.get_preview'),
	# (r'^admin/(.*)', admin.site.root),
        url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
        url(r'^admin/', include(admin.site.urls)),
	(r'^.*$','isbookshelf.error.forbidden'),
	)
# urlpatterns += patterns('',
# 	(r'^login$', 'django.contrib.auth.views.login',
# 		{'template_name':'isbookshelf/login.html'}),
# 	(r'^logout$',
# 		'django.contrib.auth.views.logout',
# 		{'template_name':'isbookshelf/logout.html'}),
# 	)
